version: '3.8'

services:
  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    volumes:
        - ./local-data:/data:z
        - ./redis.conf:/etc/keydb/keydb.conf:z

  nutritionist:
    build: .
    ports:
      - "10001:10001"
    environment:
      REDIS_HOST: keydb
      NUT_PORT: 10001
