version: '3.8'

services:
  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    volumes:
        - ./local-data:/data:z
        - ./redis.conf:/etc/keydb/keydb.conf:z

  nutritionist:
    image: hainz98/nutritionist:latest
    ports:
      - "10001:10001"
    environment:
      REDIS_HOST: keydb
    volumes:
      - ./local-data:/app/local-data:z
