version: '3.8'

services:
  keydb:
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    volumes:
        - ./local-data:/data:z
        - ./redis.conf:/etc/keydb/keydb.conf:z

  nutritionist:
    #image: hainz98/nutritionist:latest
    build: .
    ports:
      - "10001:10001"
    environment:
      REDIS_HOST: keydb
      ISSUER: https://auth.corgijan.dev/realms/nutritionist
      CLIENT_ID: ${CID}
      CLIENT_SECRET: ${SEC}
      APP_URL:  https://nutritionist.corgijan.dev
      NUT_PORT: 10001
