version: '3.8'
  c

services:
  # THIS SETUP IS ONLY FOR TESTING PRUPOSES, PLEASE DO NOT USE IT IN PRODUCTION
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    command: start --hostname=auth.corgijan.dev --proxy edge --hostname-strict-https=false  --optimized
    ports:
      - "9000:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    user: "${UID}:${GID}"
    volumes:
      - ./keycloak_data:/opt/keycloak/data/h2/:z